name: Infra Deployment
on:
  workflow_dispatch:

permissions:
  id-token: write  
  contents: write

env:
  TF_VAR_project_name: ${{ github.event.repository.name }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TF_VAR_github_token: ${{ secrets.PAT_TOKEN }}

jobs:
  infra_create_manage:
    name: 'Terraform - Apply'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: infra

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: 'Authenticate to Azure'
      uses: azure/login@v1
      with:
        client-id: 282f4bbe-1b10-49f9-976f-dbe46748f97c
        subscription-id: 40bbb825-f4ca-4762-8e52-4962cc1298d5
        tenant-id: deepakkesharitdkglobalco.onmicrosoft.com

    - uses: hashicorp/setup-terraform@v3
      name: setup-terraform

    - name: Initialise terraform backend
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
            git config --global url."https://oauth2:${{ secrets.PAT_TOKEN }}@github.com".insteadOf https://github.com
            terraform init \
              -backend-config="storage_account_name=sttdkopsinfra" \
              -backend-config="container_name=$TF_VAR_project_name" \
              -backend-config="key=terraform.tfstate" \
              -backend-config="access_key=${{ secrets.BACKEND_ACCESS_KEY }}"

    - name: Terraform plan
      id: terraform-plan
      run: terraform plan

    - name: Terraform apply
      id: terraform-apply
      run: terraform apply -auto-approve -no-color

    - name: get-vm-ip
      id: vm-ip
      run: terraform outputs
